---
title: "Final Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### [HOME](https://chandlerhaut.github.io/) | [ABOUT ME](https://chandlerhaut.github.io/about_me/) | [CV](https://chandlerhaut.github.io/about_me/CV.pdf) | [FINAL PROJECT](https://chandlerhaut.github.io/Final_Project/)

## Interactive Map (filter by Common Name)

```{r cars, echo=FALSE, message=FALSE}

library(tidyverse)
library(gapminder)
library(stringr)
library(leaflet)
library(sf)
library(shiny)
library(leaflet.extras)
library(htmltools)
library(ggmap)
library(knitr)
library(rmarkdown)
df <- read_csv('./R1_NABat_VettedObservations_NWRS2022.csv')

bats <- df %>% 
  filter(!is.na(CommonName)) %>% 
  mutate(CommonName = str_replace(CommonName, "Townsend\x92s big-eared bat", 
                                  "Townsend big-eared bat")) %>% 
  select(-"organization_name",-"species_list",-"frame", -"project_name")

nb <- #Placed the below code in the origianl bats df to keep my SHIT together
  bats %>% 
  filter(!is.na(CommonName)) %>% 
  mutate(CommonName = str_replace(CommonName, "Townsend\x92s big-eared bat", 
                                  "Townsend big-eared bat"))

#figure out what your quesiton is!!!!!!
# We want to see the population size changes over time of the bats, maybe use the animate

wdf <- 
nb %>% 
  filter(!is.na(confirmed)) %>% 
  group_by(CommonName, latitude, longitude, RefugeName) %>% 
  summarise(sum = sum(reviewed))


wdf %>% 
  leaflet() %>% 
  addProviderTiles("Esri.WorldImagery") %>% 
  addCircleMarkers(radius = 10, label = ~paste0("Common Name =", htmlEscape(CommonName),
                                              
                                              "Refuge =",htmlEscape(RefugeName)),
                   color = "blue", group = wdf$CommonName) %>% 
  addLayersControl(overlayGroups = wdf$CommonName)
```

## Distribution of Big Brown Bats


```{r pressure, echo=FALSE, message=FALSE}
p <- get_map(location = c(lat = 43.618881, lon = -116.215019), 
                           zoom = 5, maptype = "terrain")

  
bbb <- 
  wdf %>% 
  filter(CommonName == "Big brown bat")

cb <- 
  wdf %>% 
  filter(CommonName == "Canyon bat") 

lbm <- 
  wdf %>% 
  filter(CommonName == "Little brown myotis") 

ggmap(p) +
  geom_density_2d(data = bbb, aes(y=latitude, x=longitude), h = 2)
```

```{r}
ggmap(p) +
  geom_density_2d(data = cb, aes(y=latitude, x=longitude), h = 2)
ggmap(p) +
  geom_density_2d(data = lbm, aes(y=latitude, x=longitude), h = 2)
```

